/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.equipo4.bibliotecamusical.presentacion;

import javax.swing.ImageIcon;

/**
 *
 * @author oscar
 */
public class FrmLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        txtContrasenaLogin.setText("Contraseña");
    txtContrasenaLogin.setEchoChar((char) 0);
        try {
    java.net.URL urlPerfil = getClass().getResource("/imagenes/logo_musica.png");
    if (urlPerfil != null) {
        ImageIcon iconOriginal = new ImageIcon(urlPerfil);
        java.awt.Image imgEscalada = iconOriginal.getImage().getScaledInstance(
                btnIconoPerfil.getWidth(), btnIconoPerfil.getHeight(), java.awt.Image.SCALE_SMOOTH);
        btnIconoPerfil.setIcon(new ImageIcon(imgEscalada));
    }
} catch (Exception e) {
    System.out.println("No se pudo cargar la foto de perfil: " + e.getMessage());
}
        this.getContentPane().setBackground(new java.awt.Color(25, 25, 25));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCorreoLogin = new javax.swing.JTextField();
        txtContrasenaLogin = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnIconoPerfil = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(25, 25, 25));

        txtCorreoLogin.setColumns(15);
        txtCorreoLogin.setText("Usuario");
        txtCorreoLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoLoginFocusLost(evt);
            }
        });
        txtCorreoLogin.addActionListener(this::txtCorreoLoginActionPerformed);

        txtContrasenaLogin.setColumns(15);
        txtContrasenaLogin.setText("Contraseña");
        txtContrasenaLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContrasenaLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContrasenaLoginFocusLost(evt);
            }
        });
        txtContrasenaLogin.addActionListener(this::txtContrasenaLoginActionPerformed);

        btnIngresar.setBackground(new java.awt.Color(255, 0, 255));
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("ENTRAR");
        btnIngresar.addActionListener(this::btnIngresarActionPerformed);

        btnIconoPerfil.setBorderPainted(false);
        btnIconoPerfil.setContentAreaFilled(false);
        btnIconoPerfil.addActionListener(this::btnIconoPerfilActionPerformed);

        jButton1.setBackground(new java.awt.Color(255, 0, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Crear Cuenta");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIconoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCorreoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtContrasenaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIngresar)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(43, 43, 43)))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(btnIconoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCorreoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtContrasenaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIngresar)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
try {
    String correo = txtCorreoLogin.getText().trim();
    String contrasena = new String(txtContrasenaLogin.getPassword());

    if (correo.isEmpty() || contrasena.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingresa tu correo y contraseña.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    com.equipo4.bibliotecamusical.persistencia.UsuarioDAO usuarioDAO = new com.equipo4.bibliotecamusical.persistencia.UsuarioDAO(new com.equipo4.bibliotecamusical.implementaciones.ConexionDAO());
    boolean accesoConcedido = usuarioDAO.iniciarSesion(correo, contrasena);

    if (accesoConcedido) {
        javax.swing.JOptionPane.showMessageDialog(this, "¡Bienvenido a la Biblioteca Musical!", "Acceso concedido", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        FrmMenuPrincipal pantallaMenu = new FrmMenuPrincipal(correo);
        pantallaMenu.setVisible(true);

        this.dispose();
                
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos.", "Error de acceso", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error de conexión: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtCorreoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
    FrmRegistro pantallaRegistro = new FrmRegistro();
    pantallaRegistro.setVisible(true);
    
    this.dispose();
} catch (Exception ex) {
    System.out.println("Error al abrir la pantalla de registro: " + ex.getMessage());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCorreoLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoLoginFocusGained
        if (txtCorreoLogin.getText().equals("Usuario")) {
    txtCorreoLogin.setText("");
}
    }//GEN-LAST:event_txtCorreoLoginFocusGained

    private void txtCorreoLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoLoginFocusLost
        if (txtCorreoLogin.getText().isEmpty()) {
    txtCorreoLogin.setText("Usuario");
}
    }//GEN-LAST:event_txtCorreoLoginFocusLost

    private void txtContrasenaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaLoginActionPerformed

    private void txtContrasenaLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasenaLoginFocusGained
        if (String.valueOf(txtContrasenaLogin.getPassword()).equals("Contraseña")) {
    txtContrasenaLogin.setText("");
    txtContrasenaLogin.setEchoChar('•');
}
    }//GEN-LAST:event_txtContrasenaLoginFocusGained

    private void txtContrasenaLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasenaLoginFocusLost
        if (String.valueOf(txtContrasenaLogin.getPassword()).isEmpty()) {
    txtContrasenaLogin.setText("Contraseña");
    txtContrasenaLogin.setEchoChar((char) 0);
}
    }//GEN-LAST:event_txtContrasenaLoginFocusLost

    private void btnIconoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconoPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIconoPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIconoPerfil;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPasswordField txtContrasenaLogin;
    private javax.swing.JTextField txtCorreoLogin;
    // End of variables declaration//GEN-END:variables
}
