/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.equipo4.bibliotecamusical.presentacion;

import javax.swing.ImageIcon;

/**
 *
 * @author oscar
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName());
private String correoUsuarioActual;

    public FrmMenuPrincipal(String correo) {
        initComponents();
        
        this.correoUsuarioActual = correo;
        btnIconoPerfilMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIconoPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        this.getContentPane().setBackground(new java.awt.Color(25, 25, 25));
        
        try {
            
            java.net.URL urlPerfil = getClass().getResource("/imagenes/logo_musica.png");
            if (urlPerfil != null) {
                ImageIcon iconOriginal = new ImageIcon(urlPerfil);

                java.awt.Image imgEscalada = iconOriginal.getImage().getScaledInstance(
                        btnIconoPerfilMenu.getWidth(), btnIconoPerfilMenu.getHeight(), java.awt.Image.SCALE_SMOOTH);
                btnIconoPerfilMenu.setIcon(new ImageIcon(imgEscalada));
            }
        } catch (Exception e) {
            System.out.println("No se pudo cargar la foto de perfil en el menú: " + e.getMessage());
        }
        try {
    java.net.URL urlPerfil = getClass().getResource("/imagenes/imagen-de-perfil2.png");
    if (urlPerfil != null) {
        ImageIcon iconOriginal = new ImageIcon(urlPerfil);
        java.awt.Image imgEscalada = iconOriginal.getImage().getScaledInstance(
                btnIconoPerfil.getWidth(), btnIconoPerfil.getHeight(), java.awt.Image.SCALE_SMOOTH);
        btnIconoPerfil.setIcon(new ImageIcon(imgEscalada));
    }
} catch (Exception e) {
    System.out.println("No se pudo cargar la foto de perfil: " + e.getMessage());
}
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIconoPerfilMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnIconoPerfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIconoPerfilMenu.setBorderPainted(false);
        btnIconoPerfilMenu.setContentAreaFilled(false);
        btnIconoPerfilMenu.addActionListener(this::btnIconoPerfilMenuActionPerformed);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CATALOGO MUSICA");

        btnIconoPerfil.setBorderPainted(false);
        btnIconoPerfil.setContentAreaFilled(false);
        btnIconoPerfil.addActionListener(this::btnIconoPerfilActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnIconoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIconoPerfilMenu))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIconoPerfilMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIconoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(0, 217, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIconoPerfilMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconoPerfilMenuActionPerformed
        try {
    FrmMenuPrincipal menu = new FrmMenuPrincipal(this.correoUsuarioActual);
    menu.setVisible(true);
    
    this.dispose();
} catch (Exception ex) {
    System.out.println("Error al abrir el menú: " + ex.getMessage());
}
    }//GEN-LAST:event_btnIconoPerfilMenuActionPerformed

    private void btnIconoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconoPerfilActionPerformed
        try {
            FrmPerfil pantallaPerfil = new FrmPerfil(this.correoUsuarioActual);
            pantallaPerfil.setVisible(true);

            this.dispose();

        } catch (Exception ex) {
            System.out.println("Error al navegar al perfil: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnIconoPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIconoPerfil;
    private javax.swing.JButton btnIconoPerfilMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
