/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.equipo4.bibliotecamusical.presentacion;

/**
 *
 * @author oscar
 */
public class FrmPerfil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPerfil.class.getName());

    /**
     * Creates new form FrmPerfil
     */
    
    private String correoUsuarioActual;
    
    public FrmPerfil(String correo) {
        initComponents();
        this.correoUsuarioActual = correo;
        
        cargarDatosPerfil();
    }
    
    private void cargarDatosPerfil() {
        try {
            com.equipo4.bibliotecamusical.persistencia.UsuarioDAO usuarioDAO = new com.equipo4.bibliotecamusical.persistencia.UsuarioDAO();
            org.bson.Document datosUsuario = usuarioDAO.consultarPerfilPorCorreo(correoUsuarioActual);
            
            if (datosUsuario != null) {
                String nombre = datosUsuario.getString("nombreUsuario");
                lblNombreUsuario.setText("¡Hola, " + nombre + "!");
            }
        } catch (Exception ex) {
            System.out.println("Error al cargar el perfil: " + ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNuevoNombre = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        txtGeneroRestringido = new javax.swing.JTextField();
        btnBloquearGenero = new javax.swing.JButton();
        cmbTipoFav = new javax.swing.JComboBox<>();
        txtIdElemento = new javax.swing.JTextField();
        txtGeneroFav = new javax.swing.JTextField();
        btnAgregarFav = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido");

        lblNombreUsuario.setText("jLabel2");

        jButton1.setText("Cerrar Sesión");

        txtNuevoNombre.setText("Actualizar Nombre");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        txtGeneroRestringido.setText("Genero Restringido");

        btnBloquearGenero.setText("Bloquear Género");
        btnBloquearGenero.addActionListener(this::btnBloquearGeneroActionPerformed);

        cmbTipoFav.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "artista", "album", "cancion" }));
        cmbTipoFav.addActionListener(this::cmbTipoFavActionPerformed);

        txtIdElemento.setText("ID del artista o canción");

        txtGeneroFav.setText("género");

        btnAgregarFav.setText("Agregar a Favoritos");
        btnAgregarFav.addActionListener(this::btnAgregarFavActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtGeneroRestringido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnBloquearGenero)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblNombreUsuario))
                            .addComponent(jLabel1))
                        .addGap(23, 23, 23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(cmbTipoFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtGeneroFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarFav)
                    .addComponent(txtIdElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombreUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(cmbTipoFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGeneroFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarFav)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(txtGeneroRestringido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(btnBloquearGenero)
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
    String nuevoNombre = txtNuevoNombre.getText().trim();

    if (nuevoNombre.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    com.equipo4.bibliotecamusical.persistencia.UsuarioDAO usuarioDAO = new com.equipo4.bibliotecamusical.persistencia.UsuarioDAO();
    
    usuarioDAO.actualizarPerfil(correoUsuarioActual, nuevoNombre, "img/perfiles/default.png");

    lblNombreUsuario.setText("¡Hola, " + nuevoNombre + "!");
    txtNuevoNombre.setText("");

    javax.swing.JOptionPane.showMessageDialog(this, "Perfil actualizado con éxito.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBloquearGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloquearGeneroActionPerformed
        try {
    String genero = txtGeneroRestringido.getText().trim();

    if (genero.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Escribe un género musical para bloquear.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    com.equipo4.bibliotecamusical.persistencia.UsuarioDAO usuarioDAO = new com.equipo4.bibliotecamusical.persistencia.UsuarioDAO();
    usuarioDAO.agregarGeneroNoDeseado(correoUsuarioActual, genero);

    txtGeneroRestringido.setText("");
    javax.swing.JOptionPane.showMessageDialog(this, "El género '" + genero + "' ha sido bloqueado.\nSe han eliminado de tus favoritos los elementos relacionados.", "Operación Exitosa", javax.swing.JOptionPane.INFORMATION_MESSAGE);

} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error al bloquear el género: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnBloquearGeneroActionPerformed

    private void btnAgregarFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFavActionPerformed
        try {
    String tipo = cmbTipoFav.getSelectedItem().toString();
    String idElemento = txtIdElemento.getText().trim();
    String genero = txtGeneroFav.getText().trim();

    if (idElemento.isEmpty() || genero.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor llena el ID y el género.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    com.equipo4.bibliotecamusical.persistencia.UsuarioDAO usuarioDAO = new com.equipo4.bibliotecamusical.persistencia.UsuarioDAO();
    usuarioDAO.agregarAFavoritos(correoUsuarioActual, tipo, idElemento, genero);

    txtIdElemento.setText("");
    txtGeneroFav.setText("");
    
    javax.swing.JOptionPane.showMessageDialog(this, "¡Agregado a favoritos exitosamente!", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

} catch (IllegalStateException ex) {
    javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Género Restringido", javax.swing.JOptionPane.WARNING_MESSAGE);
} catch (IllegalArgumentException ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "El ID ingresado no es válido.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
        
    }//GEN-LAST:event_btnAgregarFavActionPerformed

    private void cmbTipoFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoFavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoFavActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarFav;
    private javax.swing.JButton btnBloquearGenero;
    private javax.swing.JComboBox<String> cmbTipoFav;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JTextField txtGeneroFav;
    private javax.swing.JTextField txtGeneroRestringido;
    private javax.swing.JTextField txtIdElemento;
    private javax.swing.JTextField txtNuevoNombre;
    // End of variables declaration//GEN-END:variables
}
