/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.equipo4.bibliotecamusical.presentacion;

import javax.swing.ImageIcon;

/**
 *
 * @author oscar
 */
public class FrmPerfil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPerfil.class.getName());

    /**
     * Creates new form FrmPerfil
     */
    
    private String correoUsuarioActual;
    
    public FrmPerfil(String correo) {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(25, 25, 25));
        try {
    java.net.URL urlLogo = getClass().getResource("/imagenes/logo_musica.png"); 
    if (urlLogo != null) {
        ImageIcon iconOriginal = new ImageIcon(urlLogo);
        java.awt.Image imgEscalada = iconOriginal.getImage().getScaledInstance(
                btnLogoMenu.getWidth(), btnLogoMenu.getHeight(), java.awt.Image.SCALE_SMOOTH);
        btnLogoMenu.setIcon(new ImageIcon(imgEscalada));
    }
} catch (Exception e) {
    System.out.println("No se pudo cargar el logo: " + e.getMessage());
}

try {
    java.net.URL urlPerfil = getClass().getResource("/imagenes/imagen-de-perfil2.png");
    if (urlPerfil != null) {
        ImageIcon iconOriginal = new ImageIcon(urlPerfil);
        java.awt.Image imgEscalada = iconOriginal.getImage().getScaledInstance(
                btnIconoPerfil.getWidth(), btnIconoPerfil.getHeight(), java.awt.Image.SCALE_SMOOTH);
        btnIconoPerfil.setIcon(new ImageIcon(imgEscalada));
    }
} catch (Exception e) {
    System.out.println("No se pudo cargar la foto de perfil: " + e.getMessage());
}
        this.correoUsuarioActual = correo;
        btnLogoMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIconoPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cargarDatosPerfil();
    }
    
    private void cargarDatosPerfil() {
        try {
            com.equipo4.bibliotecamusical.persistencia.UsuarioDAO usuarioDAO = new com.equipo4.bibliotecamusical.persistencia.UsuarioDAO(new com.equipo4.bibliotecamusical.implementaciones.ConexionDAO());
            com.equipo4.bibliotecamusical.entidades.Usuario datosUsuario = usuarioDAO.consultarPerfilPorCorreo(correoUsuarioActual);

            if (datosUsuario != null) {
                lblNombreUsuario.setText("¡Hola, " + datosUsuario.getNombreUsuario() + "!");
            }
        } catch (Exception ex) {
            System.out.println("Error al cargar el perfil: " + ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        txtNuevoNombre = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        txtGeneroRestringido = new javax.swing.JTextField();
        btnBloquearGenero = new javax.swing.JButton();
        cmbTipoFav = new javax.swing.JComboBox<>();
        txtIdElemento = new javax.swing.JTextField();
        txtGeneroFav = new javax.swing.JTextField();
        btnAgregarFav = new javax.swing.JButton();
        btnLogoMenu = new javax.swing.JButton();
        btnIconoPerfil = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(25, 25, 25));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido");

        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("jLabel2");

        btnCerrarSesion.setBackground(new java.awt.Color(255, 0, 255));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        txtNuevoNombre.setColumns(15);
        txtNuevoNombre.setText("Actualizar Nombre");

        btnActualizar.setBackground(new java.awt.Color(255, 0, 255));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        txtGeneroRestringido.setColumns(15);
        txtGeneroRestringido.setText("Genero Restringido");
        txtGeneroRestringido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGeneroRestringidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGeneroRestringidoFocusLost(evt);
            }
        });
        txtGeneroRestringido.addActionListener(this::txtGeneroRestringidoActionPerformed);

        btnBloquearGenero.setBackground(new java.awt.Color(255, 0, 255));
        btnBloquearGenero.setForeground(new java.awt.Color(255, 255, 255));
        btnBloquearGenero.setText("Bloquear Género");
        btnBloquearGenero.addActionListener(this::btnBloquearGeneroActionPerformed);

        cmbTipoFav.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "artista", "album", "cancion" }));
        cmbTipoFav.addActionListener(this::cmbTipoFavActionPerformed);

        txtIdElemento.setColumns(15);
        txtIdElemento.setText("ID del artista o canción");
        txtIdElemento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdElementoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdElementoFocusLost(evt);
            }
        });

        txtGeneroFav.setColumns(15);
        txtGeneroFav.setText("género");
        txtGeneroFav.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGeneroFavFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGeneroFavFocusLost(evt);
            }
        });
        txtGeneroFav.addActionListener(this::txtGeneroFavActionPerformed);

        btnAgregarFav.setBackground(new java.awt.Color(255, 0, 255));
        btnAgregarFav.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarFav.setText("Agregar a Favoritos");
        btnAgregarFav.addActionListener(this::btnAgregarFavActionPerformed);

        btnLogoMenu.setBorderPainted(false);
        btnLogoMenu.setContentAreaFilled(false);
        btnLogoMenu.addActionListener(this::btnLogoMenuActionPerformed);

        btnIconoPerfil.setBorderPainted(false);
        btnIconoPerfil.setContentAreaFilled(false);
        btnIconoPerfil.addActionListener(this::btnIconoPerfilActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnCerrarSesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblNombreUsuario)))
                        .addGap(64, 64, 64)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(cmbTipoFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnIconoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtGeneroRestringido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnBloquearGenero, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(btnAgregarFav)))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtGeneroFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIconoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(cmbTipoFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombreUsuario)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGeneroFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarFav)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(txtGeneroRestringido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(btnBloquearGenero)
                .addGap(16, 16, 16)
                .addComponent(btnCerrarSesion)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
    String nuevoNombre = txtNuevoNombre.getText().trim();

    if (nuevoNombre.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    com.equipo4.bibliotecamusical.persistencia.UsuarioDAO usuarioDAO = new com.equipo4.bibliotecamusical.persistencia.UsuarioDAO(new com.equipo4.bibliotecamusical.implementaciones.ConexionDAO());

    usuarioDAO.actualizarPerfil(correoUsuarioActual, nuevoNombre, "img/perfiles/default.png");

    lblNombreUsuario.setText("¡Hola, " + nuevoNombre + "!");
    txtNuevoNombre.setText("");

    javax.swing.JOptionPane.showMessageDialog(this, "Perfil actualizado con éxito.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBloquearGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloquearGeneroActionPerformed
        try {
    String genero = txtGeneroRestringido.getText().trim();

    if (genero.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Escribe un género musical para bloquear.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    com.equipo4.bibliotecamusical.persistencia.UsuarioDAO usuarioDAO = new com.equipo4.bibliotecamusical.persistencia.UsuarioDAO(new com.equipo4.bibliotecamusical.implementaciones.ConexionDAO());
    usuarioDAO.agregarGeneroNoDeseado(correoUsuarioActual, genero);

    txtGeneroRestringido.setText("");
    javax.swing.JOptionPane.showMessageDialog(this, "El género '" + genero + "' ha sido bloqueado.\nSe han eliminado de tus favoritos los elementos relacionados.", "Operación Exitosa", javax.swing.JOptionPane.INFORMATION_MESSAGE);

} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error al bloquear el género: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnBloquearGeneroActionPerformed

    private void btnAgregarFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFavActionPerformed
        try {
        String idIngresado = txtIdElemento.getText().trim();
        String generoIngresado = txtGeneroFav.getText().trim();
        String tipoSeleccionado = cmbTipoFav.getSelectedItem().toString();

        if (idIngresado.isEmpty() || generoIngresado.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llena todos los campos.");
            return;
        }

        com.equipo4.bibliotecamusical.persistencia.UsuarioDAO usuarioDAO = new com.equipo4.bibliotecamusical.persistencia.UsuarioDAO(new com.equipo4.bibliotecamusical.implementaciones.ConexionDAO());
        usuarioDAO.agregarAFavoritos(this.correoUsuarioActual, tipoSeleccionado, idIngresado, generoIngresado);

        javax.swing.JOptionPane.showMessageDialog(this, "¡Agregado a favoritos!");

        txtIdElemento.setText("ID del artista o canción");
        txtGeneroFav.setText("género");

    } catch (IllegalArgumentException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "El ID ingresado no tiene un formato válido de MongoDB.");
    } catch (com.equipo4.bibliotecamusical.excepciones.GeneroRestringidoException | com.equipo4.bibliotecamusical.excepciones.ElementoNoEncontradoException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al agregar a favoritos: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnAgregarFavActionPerformed

    private void cmbTipoFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoFavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoFavActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int opcion = javax.swing.JOptionPane.showConfirmDialog(this, 
        "¿Estás seguro de que deseas cerrar sesión?", 
        "Cerrar Sesión", 
        javax.swing.JOptionPane.YES_NO_OPTION, 
        javax.swing.JOptionPane.QUESTION_MESSAGE);

if (opcion == javax.swing.JOptionPane.YES_OPTION) {
    FrmLogin pantallaLogin = new FrmLogin();
    pantallaLogin.setVisible(true);
    
    this.dispose();
}
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnIconoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconoPerfilActionPerformed
        try {
    FrmPerfil pantallaPerfil = new FrmPerfil(this.correoUsuarioActual);
    pantallaPerfil.setVisible(true);
    
    this.dispose();
    
} catch (Exception ex) {
    System.out.println("Error al navegar al perfil: " + ex.getMessage());
}
    }//GEN-LAST:event_btnIconoPerfilActionPerformed

    private void btnLogoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoMenuActionPerformed
        try {
    FrmMenuPrincipal menu = new FrmMenuPrincipal(this.correoUsuarioActual);
    menu.setVisible(true);
    
    this.dispose();
} catch (Exception ex) {
    System.out.println("Error al abrir el menú: " + ex.getMessage());
}
    }//GEN-LAST:event_btnLogoMenuActionPerformed

    private void txtIdElementoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdElementoFocusGained
        if (txtIdElemento.getText().equals("ID del artista o canción")) {
    txtIdElemento.setText("");
}
    }//GEN-LAST:event_txtIdElementoFocusGained

    private void txtIdElementoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdElementoFocusLost
        if (txtIdElemento.getText().isEmpty()) {
    txtIdElemento.setText("ID del artista o canción");
}
    }//GEN-LAST:event_txtIdElementoFocusLost

    private void txtGeneroFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroFavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroFavActionPerformed

    private void txtGeneroFavFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGeneroFavFocusGained
        if (txtGeneroFav.getText().equals("Género")) {
        txtGeneroFav.setText(""); 
    }

    }//GEN-LAST:event_txtGeneroFavFocusGained

    private void txtGeneroFavFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGeneroFavFocusLost
        if (txtGeneroFav.getText().isEmpty()) {
        txtGeneroFav.setText("Género"); 
        }
    }//GEN-LAST:event_txtGeneroFavFocusLost

    private void txtGeneroRestringidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroRestringidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroRestringidoActionPerformed

    private void txtGeneroRestringidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGeneroRestringidoFocusGained
        if (txtGeneroRestringido.getText().equals("Genero Restringido")) {
        txtGeneroRestringido.setText(""); 
    }//GEN-LAST:event_txtGeneroRestringidoFocusGained
    }
    private void txtGeneroRestringidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGeneroRestringidoFocusLost
        if (txtGeneroRestringido.getText().isEmpty()) {
        txtGeneroRestringido.setText("Genero Restringido"); 
        }
    }//GEN-LAST:event_txtGeneroRestringidoFocusLost

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarFav;
    private javax.swing.JButton btnBloquearGenero;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnIconoPerfil;
    private javax.swing.JButton btnLogoMenu;
    private javax.swing.JComboBox<String> cmbTipoFav;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JTextField txtGeneroFav;
    private javax.swing.JTextField txtGeneroRestringido;
    private javax.swing.JTextField txtIdElemento;
    private javax.swing.JTextField txtNuevoNombre;
    // End of variables declaration//GEN-END:variables
}
